<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $guarded = [];

    protected  $casts = [
        'completed' => 'boolean'
    ];
    protected $touches = ['project'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($task){
            $task->project->recordActivity('created task');
        });

        static::deleted(function($task){
            $task->project->recordActivity('deleted task');
        });
    }

    public function complete()
    {
        $this->update(['completed' => true]);

        $this->project->recordActivity('completed task');
    }

    public function incomplete()
    {
        $this->update(['completed' => false]);

        $this->project->recordActivity('uncompleted task');
    }

    public function project()
    {
       return $this->belongsTo(Project::class);
    }

    public function path()
    {
       return "/projects/{$this->project->id}/tasks/{$this->id}";
    }

}
